import { PageCanvas } from "../components/PageCanvas";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Wings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Wings/favicon.ico" />
      </Head>
      <PageCanvas />
    </>
  );
}
